server:
  port: 8080
  mode: development

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: 123456
  dbname: douyin_mall
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

log:
  level: debug
  filename: ./logs/app.log
  maxsize: 100
  maxage: 7
  maxbackups: 10